### ISSUE TITLE
Most recent update causing issues 

### ISSUE THREAD

**Issue by nightingalephillip** [brightio/penelope#27]
I just got the latest update . It seems like it's having an issue grabbing the interface. 

![image](https://github.com/user-attachments/assets/75443669-219c-4e42-af51-b3cd549895cc)

```
Traceback (most recent call last):
  File "/root/penelope/./penelope.py", line 4190, in <module>
    main()
  File "/root/penelope/./penelope.py", line 4185, in main
    Listener(port=port)
  File "/root/penelope/./penelope.py", line 1176, in __init__
    self.host = Interfaces().translate(self.host)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/penelope/./penelope.py", line 3580, in translate
    if iface_ip in self.list:
                   ^^^^^^^^^
  File "/root/penelope/./penelope.py", line 3600, in list
    interfaces.append((interface_stack.pop(), ip[1]))
                       ^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list
```

**Comment by nightingalephillip** [comment]
I made some  modifications starting at line 3599. 
![image](https://github.com/user-attachments/assets/960d78a1-811d-483d-b534-62896518375f)

```
if ip:
						if interface_stack:
							interfaces.append((interface_stack.pop(), ip[1]))
						else:
							logger.error("No interface found for IP: {}".format(ip[1]))
```
The result is this.

![image](https://github.com/user-attachments/assets/527a76d8-469d-4a92-a637-eb8bb07fb3d6)

So it looks like it get's an error if there is an interface it can't find. For the record, I would only need to use eth0 or tun0.  
Here are my interfaces.

![image](https://github.com/user-attachments/assets/5b46b300-7b5d-4ccd-95c5-a01c5203ef62)

**Comment by brightio** [comment]
Hi @nightingalephillip, thanks for reporting this! Can you please try now?

**Comment by nightingalephillip** [comment]
Looks like it's good to go! Really Appreciate it and good job!

**Comment by joshoram80** [comment]
Using 0.12.3 and a fresh Kali install, this is still happening

```
Traceback (most recent call last):
  File "/home/josh/scripts/penelope.py", line 4581, in <module>
    main()
  File "/home/josh/scripts/penelope.py", line 4550, in main                                                                                                            
    print(Interfaces())                                                                                                                                                
  File "/home/josh/scripts/penelope.py", line 129, in __str__                                                                                                          
    for name, ip in self.list.items():                                                                                                                                 
                    ^^^^^^^^^                                                                                                                                          
  File "/home/josh/scripts/penelope.py", line 157, in list                                                                                                             
    interfaces.append((interface_stack.pop(), ip[1]))                                                                                                                  
                       ^^^^^^^^^^^^^^^^^^^^^                                                                                                                           
IndexError: pop from empty list    
```

Interestingly, it worked fine before I did a fresh install on a new VM

**Comment by brightio** [comment]
Can you please show me the output of the `ip addr` command?

**Comment by joshoram80** [comment]
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:63:41:28 brd ff:ff:ff:ff:ff:ff
    inet 10.0.88.10/24 brd 10.0.88.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet 10.0.88.252/24 brd 10.0.88.255 scope global secondary dynamic noprefixroute eth0
       valid_lft 1667sec preferred_lft 1667sec
    inet6 fe80::8f18:917b:c8ba:b91/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 10.4.96.28/17 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::2c45:216:7055:a43a/64 scope link stable-privacy proto kernel_ll 
       valid_lft forever preferred_lft forever

```

No issues with 10.0

**Comment by brightio** [comment]
What do you mean with 10.0? 
Are you sure that you are running the latest version?

**Comment by joshoram80** [comment]
Sorry typo. I went back to 0.11.0 for now as it works. 0.12.3 has the error

**Comment by brightio** [comment]
@joshoram80 this should be fixed now. Can you please try again with the newest version? (0.12.4) Thank you!

**Comment by joshoram80** [comment]
Seems to work now! Awesome thanks :D

**Comment by brightio** [comment]
Thank you very much for reporting bugs! Cheers!
